# Generated by Django 5.1 on 2026-03-11 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(help_text='e.g. "product", "blog_post", "page_section"', max_length=100)),
                ('data', models.JSONField(default=dict)),
                ('search_index', models.TextField(blank=True, help_text='Auto-populated text for full-text search')),
                ('slug', models.SlugField(blank=True, help_text='Auto-extracted from data["slug"] or data["title"]', max_length=255)),
                ('template_name', models.CharField(blank=True, help_text='Optional override template for entity detail view', max_length=500)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='sites.site')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('site', 'entity_type', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='URL path, e.g. /about/', max_length=500)),
                ('template_name', models.CharField(help_text='Path to the template file, e.g. cms/about.html', max_length=500)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='sites.site')),
            ],
            options={
                'ordering': ['path'],
                'unique_together': {('site', 'path')},
            },
        ),
        migrations.CreateModel(
            name='SchemaEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=500)),
                ('block_key', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('field_type', models.CharField(default='text', help_text='text, richtext, image, number, color, boolean', max_length=50)),
                ('is_list', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('template_name', 'block_key', 'item_name')},
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Matches the {% editable "key" %} tag', max_length=255)),
                ('scope', models.CharField(choices=[('local', 'Local (per-page)'), ('global', 'Global (site-wide)')], default='local', max_length=10)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='sites.site')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='cms.contententity')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='cms.page')),
            ],
            options={
                'unique_together': {('site', 'key', 'page', 'scope')},
            },
        ),
    ]
