# Generated by Django 5.1.14 on 2026-03-12 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['sort_order', 'path']},
        ),
        migrations.AddField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent page for hierarchical structure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.page'),
        ),
        migrations.AddField(
            model_name='page',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Sort order among siblings'),
        ),
    ]
